
services:
  my_server:
    build:
      context: my_server
      dockerfile: Dockerfile
    container_name: my_server_container
    ports:
      - "127.0.0.1:8080:8080"
    # depends_on:
    #   - sqlite
    restart: on-failure
    environment:
      TZ: "Europe/Moscow"
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8080/api/healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 5s

  # reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      # - ./log/report:/opt/report
      # - ./.htpasswd:/opt/.htpasswd
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - my_server
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 5s

volumes:
  # database_volume:
  my_server:
